### ISSUE TITLE
Move Docker files back to root

### ISSUE THREAD

**Issue by lawliet89** [datagovsg/airflow-pipeline#23]
Reasons:
 - It is unconventional to have them in a sub-directory
 - Docker does not allow you to copy files "above" a directory (i.e. `COPY ../xxx` will fail)
 - Unnecessary extra flags to build an image, so more places to make mistakes.

**Comment by chrissng** [comment]
your have a point. my intention was to keep the root directory tidy. 

please review my PR https://github.com/datagovsg/airflow-pipeline/pull/27

**Comment by lawliet89** [comment]
Fixed in #27
