### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by leeshangqian** [datagovsg/airflow-pipeline#38]
Is it possible to have both python 2 and 3 supported at the same time?

**Comment by chrissng** [comment]
It is possible to switch over to python 3 by pointing the line of this Dockerfile (https://github.com/datagovsg/airflow-pipeline/blob/master/Dockerfile#L1) to the Dockerfile referenced here https://github.com/datagovsg/python-spark/blob/master/python3/spark1.6/Dockerfile

A separate effort is also required to auto build the python3 `python-spark` docker image.
