### ISSUE TITLE
USER: unbound variable

### ISSUE THREAD

**Issue by Manavbagai11** [datagovsg/airflow-pipeline#44]
While running docker image, I am receiving the following error:
/entrypoint.sh: line 7: USER: unbound variable.

Code of entrypoint.sh.

    #!/bin/bash
set -euo pipefail

export SPARK_DIST_CLASSPATH=$(hadoop classpath)
POSTGRES_TIMEOUT=60

echo "Running as: ${USER}"
if [ "${USER}" != "root" ]; then
  echo "Changing owner of files in ${AIRFLOW_HOME} to ${USER}"
  chown -R "${USER}" ${AIRFLOW_HOME}
fi

set +e

Declaration of Environment variable user in Docker File:

# Delay creation of user and group
ONBUILD ARG THEUSER=afpuser
ONBUILD ARG THEGROUP=hadoop

ONBUILD ENV USER ${THEUSER}
ONBUILD ENV GROUP ${THEGROUP}
ONBUILD RUN groupadd -r "${GROUP}" && useradd -rmg "${GROUP}" "${USER}"

**Comment by chrissng** [comment]
You would need to create a child image that is derived from `datagovsg/airflow-pipeline:latest`.

**Comment by Manavbagai11** [comment]
Thanks for Replying. The above problem was solved.
After building the child image and running, connection with db cannot be built
Checking datbase connection /dev/tcp/localhost/5999
Waiting for database /dev/tcp/localhost/5999

**Comment by chrissng** [comment]
Airflow requires a database to record metadata such as DAGs and tasks states. Do take a look at the provided docker-compose.yml file to have some idea; the setup consists of postgresql, airflow scheduler and airflow web server.

**Comment by manavbagai** [comment]
Sir, What should I do to make above running. I have even added RUN set -ex pip install airflow[postgres] to my child image but the problem didn't solved.

**Comment by chrissng** [comment]
You can start the services by running `docker-compose -f docker-compose.yml up --build -d`.

Closing this issue. See PR: https://github.com/datagovsg/airflow-pipeline/pull/56
