### ISSUE TITLE
Reduce image size by deleting docs

### ISSUE THREAD

**Issue by xkjyeah** [datagovsg/airflow-pipeline#51]
Here's a list of the top biggest subdirs from /:

19396	/usr/share/perl
21204	/usr/lib/python2.7/dist-packages
28280	/opt/sqoop-1.4.6.bin__hadoop-2.0.4-alpha
32544	/lib
33452	/usr/include
37848	/usr/bin
40256	/var/lib/dpkg/info
41480	/var/lib/dpkg
41648	/usr/lib/python2.7
49452	/usr/local/lib/python2.7
51416	/var/lib
53928	/var
56680	/usr/local/lib
57504	/usr/local
62036	/usr/lib/gcc/x86_64-linux-gnu
62040	/usr/lib/gcc
91716	/usr/share/locale
95188	/opt/hadoop/share/doc
100252	/usr/lib/jvm/java-7-openjdk-amd64
100260	/usr/lib/jvm
217952	/opt/hadoop/share/hadoop
241476	/usr/lib/x86_64-linux-gnu
310444	/opt/spark-1.6.1/lib
313144	/opt/hadoop/share
318940	/opt/hadoop
322208	/opt/spark-1.6.1
453724	/usr/share/doc/openjdk-7-jre-headless
472720	/usr/lib
534528	/usr/share/doc
669432	/opt
700440	/usr/share
1303788	/usr
2074236	/

Seems like it would be a great idea to save 500MB by deleting /usr/share/doc

**Comment by chrissng** [comment]
Sounds feasible. There's also a related discussion here: https://github.com/tianon/docker-brew-debian/issues/48
